### ISSUE TITLE
Comment is sent empty

### ISSUE THREAD

**Issue by OKNoah** [bglick/angular-feedback#4]
I'm seeing the request sent like this even when text is entered:

`{ feedback: { comment: '' } }`

**Comment by bglick** [comment]
@OKNoah What version of angular are you running?

**Comment by OKNoah** [comment]
`1.2.28`

**Comment by OKNoah** [comment]
After upgrading, I see the same thing in Angular 1.3.8

**Comment by bglick** [comment]
I'm seeing the unit tests fail.  This was originally built against 1.0.x

I'm going to see if I can figure it out now against 1.2.28 for you.

On Thu, Mar 19, 2015 at 3:30 PM, OKNoah <notifications@github.com> wrote:

> After upgrading, I see the same thing in Angular 1.3.8
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bglick/angular-feedback/issues/4#issuecomment-83731682>
> .
>



-- 
Brian Glick
http://brian-glick.com

**Comment by OKNoah** [comment]
OK, I'm taking a look too.

**Comment by OKNoah** [comment]
I believe it's just line 18 (in compiled JS version, not copfescript) that says

    scope.feedback.comment = '';

**Comment by bglick** [comment]
That line is supposed to clear the box after the call.  I'm checking
something else.

On Thu, Mar 19, 2015 at 4:12 PM, OKNoah <notifications@github.com> wrote:

> I believe it's just line 18 (in compiled JS version, not copfescript) that
> says
>
> scope.feedback.comment = '';
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bglick/angular-feedback/issues/4#issuecomment-83744301>
> .
>



-- 
Brian Glick
http://brian-glick.com

**Comment by OKNoah** [comment]
I can make a pull request for that if you like.

**Comment by bglick** [comment]
@OKNoah please test with latest build in /dist folder.  I tested against 1.2.28, but it the fix should work against most versions.  Let me know and I'll close the issue.

**Comment by OKNoah** [comment]
Works great, thank you!
